valuesets:
  - name: genomic
    semantic_units:
      - genomic_value_group
      - genomic_mapped_types
  - name: modifiers
    semantic_units:
      - modifier_fields
      - modifier_tables
  - name: types
    semantic_units: 
      - treatment_episode_types
      - disease_episode_types
      - source_types
  - name: treatment_modifiers
    semantic_units: 
      - treatment_intent
      - treatment_modality
      - treatment_modifier_values
  - name: condition_modifiers
    semantic_units: 
      - condition_modifier_values
      - tumor_grade
      - numeric_condition_modifiers
      - condition_status
  - name: nlp
    semantic_units:
      - document_type
      - document_encoding
      - document_language
  - name: cancer_procedures
    semantic_units: 
      - cancer_consult_types
      - encounter_provider_specialty
      - cancer_procedure_types
      - procedures_by_location
  - name: measurements_numeric
    semantic_units:
      - body_size_units
      - body_size_measurements
      - lab_measurements
      - smoking_numeric
      - proms_numeric
      - performance_status_measurements
  - name: staging
    semantic_units:
      - t_stage_concepts
      - n_stage_concepts
      - m_stage_concepts
      - group_stage_concepts
      - stage_edition
  - name: visits
    semantic_units:
      - visit_modalities
  - name: observations
    semantic_units:
      - demography_concepts
      - sact_concepts
  - name: unknowns
    semantic_units:
      - unknowns